# Generated by Django 3.0.5 on 2021-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'Shipped'), (4, 'Delivered'), (2, 'Ready For Shipment'), (1, 'Not Packed')], default=1),
        ),
    ]
