# Generated by Django 3.0.5 on 2021-10-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20211002_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'Shipped'), (2, 'Ready For Shipment'), (1, 'Not Packed'), (4, 'Delivered')], default=1),
        ),
    ]
