# Generated by Django 3.0.5 on 2021-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20211002_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Ready For Shipment'), (4, 'Delivered'), (3, 'Shipped'), (1, 'Not Packed')], default=1),
        ),
    ]
