# Generated by Django 3.0.5 on 2021-10-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20211013_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (2, 'Ready For Shipment'), (1, 'Not Packed'), (3, 'Shipped')], default=1),
        ),
    ]
