# Generated by Django 3.0.5 on 2021-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20211002_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Packed'), (3, 'Shipped'), (4, 'Delivered'), (2, 'Ready For Shipment')], default=1),
        ),
    ]
