# Generated by Django 3.0.5 on 2021-10-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_auto_20211008_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (3, 'Shipped'), (1, 'Not Packed'), (2, 'Ready For Shipment')], default=1),
        ),
    ]
