# Generated by Django 3.0.5 on 2021-10-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_auto_20211008_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (1, 'Not Packed'), (3, 'Shipped'), (2, 'Ready For Shipment')], default=1),
        ),
    ]
