# Generated by Django 3.0.5 on 2021-10-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_auto_20211008_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='firstapp/productimages'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'Shipped'), (2, 'Ready For Shipment'), (1, 'Not Packed'), (4, 'Delivered')], default=1),
        ),
    ]
